package com.prince.myproj.platform.av.models;

import java.io.Serializable;

public class AvCateModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_cate.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_cate.cate
     *
     * @mbggenerated
     */
    private String cate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_cate.source_url
     *
     * @mbggenerated
     */
    private String sourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_cate.id
     *
     * @return the value of av_cate.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_cate.id
     *
     * @param id the value for av_cate.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_cate.cate
     *
     * @return the value of av_cate.cate
     *
     * @mbggenerated
     */
    public String getCate() {
        return cate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_cate.cate
     *
     * @param cate the value for av_cate.cate
     *
     * @mbggenerated
     */
    public void setCate(String cate) {
        this.cate = cate == null ? null : cate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_cate.source_url
     *
     * @return the value of av_cate.source_url
     *
     * @mbggenerated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_cate.source_url
     *
     * @param sourceUrl the value for av_cate.source_url
     *
     * @mbggenerated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AvCateModel other = (AvCateModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCate() == null ? other.getCate() == null : this.getCate().equals(other.getCate()))
            && (this.getSourceUrl() == null ? other.getSourceUrl() == null : this.getSourceUrl().equals(other.getSourceUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCate() == null) ? 0 : getCate().hashCode());
        result = prime * result + ((getSourceUrl() == null) ? 0 : getSourceUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cate=").append(cate);
        sb.append(", sourceUrl=").append(sourceUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}