package com.prince.myproj.platform.av.models;

import java.io.Serializable;
import java.util.Date;

public class AvMoiveModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.length
     *
     * @mbggenerated
     */
    private Integer length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.director
     *
     * @mbggenerated
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.maker
     *
     * @mbggenerated
     */
    private String maker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.runner
     *
     * @mbggenerated
     */
    private String runner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.big_img
     *
     * @mbggenerated
     */
    private String bigImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.small_img
     *
     * @mbggenerated
     */
    private String smallImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.source_url
     *
     * @mbggenerated
     */
    private String sourceUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.run_date
     *
     * @mbggenerated
     */
    private Date runDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_moive.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.id
     *
     * @return the value of av_moive.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.id
     *
     * @param id the value for av_moive.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.code
     *
     * @return the value of av_moive.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.code
     *
     * @param code the value for av_moive.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.length
     *
     * @return the value of av_moive.length
     *
     * @mbggenerated
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.length
     *
     * @param length the value for av_moive.length
     *
     * @mbggenerated
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.director
     *
     * @return the value of av_moive.director
     *
     * @mbggenerated
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.director
     *
     * @param director the value for av_moive.director
     *
     * @mbggenerated
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.maker
     *
     * @return the value of av_moive.maker
     *
     * @mbggenerated
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.maker
     *
     * @param maker the value for av_moive.maker
     *
     * @mbggenerated
     */
    public void setMaker(String maker) {
        this.maker = maker == null ? null : maker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.runner
     *
     * @return the value of av_moive.runner
     *
     * @mbggenerated
     */
    public String getRunner() {
        return runner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.runner
     *
     * @param runner the value for av_moive.runner
     *
     * @mbggenerated
     */
    public void setRunner(String runner) {
        this.runner = runner == null ? null : runner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.big_img
     *
     * @return the value of av_moive.big_img
     *
     * @mbggenerated
     */
    public String getBigImg() {
        return bigImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.big_img
     *
     * @param bigImg the value for av_moive.big_img
     *
     * @mbggenerated
     */
    public void setBigImg(String bigImg) {
        this.bigImg = bigImg == null ? null : bigImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.small_img
     *
     * @return the value of av_moive.small_img
     *
     * @mbggenerated
     */
    public String getSmallImg() {
        return smallImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.small_img
     *
     * @param smallImg the value for av_moive.small_img
     *
     * @mbggenerated
     */
    public void setSmallImg(String smallImg) {
        this.smallImg = smallImg == null ? null : smallImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.source_url
     *
     * @return the value of av_moive.source_url
     *
     * @mbggenerated
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.source_url
     *
     * @param sourceUrl the value for av_moive.source_url
     *
     * @mbggenerated
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.run_date
     *
     * @return the value of av_moive.run_date
     *
     * @mbggenerated
     */
    public Date getRunDate() {
        return runDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.run_date
     *
     * @param runDate the value for av_moive.run_date
     *
     * @mbggenerated
     */
    public void setRunDate(Date runDate) {
        this.runDate = runDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.create_time
     *
     * @return the value of av_moive.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.create_time
     *
     * @param createTime the value for av_moive.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_moive.title
     *
     * @return the value of av_moive.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_moive.title
     *
     * @param title the value for av_moive.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AvMoiveModel other = (AvMoiveModel) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getLength() == null ? other.getLength() == null : this.getLength().equals(other.getLength()))
            && (this.getDirector() == null ? other.getDirector() == null : this.getDirector().equals(other.getDirector()))
            && (this.getMaker() == null ? other.getMaker() == null : this.getMaker().equals(other.getMaker()))
            && (this.getRunner() == null ? other.getRunner() == null : this.getRunner().equals(other.getRunner()))
            && (this.getBigImg() == null ? other.getBigImg() == null : this.getBigImg().equals(other.getBigImg()))
            && (this.getSmallImg() == null ? other.getSmallImg() == null : this.getSmallImg().equals(other.getSmallImg()))
            && (this.getSourceUrl() == null ? other.getSourceUrl() == null : this.getSourceUrl().equals(other.getSourceUrl()))
            && (this.getRunDate() == null ? other.getRunDate() == null : this.getRunDate().equals(other.getRunDate()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getLength() == null) ? 0 : getLength().hashCode());
        result = prime * result + ((getDirector() == null) ? 0 : getDirector().hashCode());
        result = prime * result + ((getMaker() == null) ? 0 : getMaker().hashCode());
        result = prime * result + ((getRunner() == null) ? 0 : getRunner().hashCode());
        result = prime * result + ((getBigImg() == null) ? 0 : getBigImg().hashCode());
        result = prime * result + ((getSmallImg() == null) ? 0 : getSmallImg().hashCode());
        result = prime * result + ((getSourceUrl() == null) ? 0 : getSourceUrl().hashCode());
        result = prime * result + ((getRunDate() == null) ? 0 : getRunDate().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", length=").append(length);
        sb.append(", director=").append(director);
        sb.append(", maker=").append(maker);
        sb.append(", runner=").append(runner);
        sb.append(", bigImg=").append(bigImg);
        sb.append(", smallImg=").append(smallImg);
        sb.append(", sourceUrl=").append(sourceUrl);
        sb.append(", runDate=").append(runDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", title=").append(title);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}