package com.prince.myproj.platform.av.dao;

import com.prince.myproj.platform.av.models.AvActorCodeModel;

public interface AvActorCodeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_actor_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_actor_code
     *
     * @mbggenerated
     */
    int insert(AvActorCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_actor_code
     *
     * @mbggenerated
     */
    int insertSelective(AvActorCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_actor_code
     *
     * @mbggenerated
     */
    AvActorCodeModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_actor_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AvActorCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_actor_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AvActorCodeModel record);
}