package com.prince.myproj.platform.av.dao;

import com.prince.myproj.platform.av.models.AvCateModel;

public interface AvCateModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    int insert(AvCateModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    int insertSelective(AvCateModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    AvCateModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AvCateModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_cate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AvCateModel record);
}