package com.prince.myproj.platform.av.dao;

import com.prince.myproj.platform.av.models.AvMoiveModel;

import java.util.List;

public interface AvMoiveModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    int insert(AvMoiveModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    int insertSelective(AvMoiveModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    AvMoiveModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AvMoiveModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_moive
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AvMoiveModel record);

    List<AvMoiveModel> selectByCode(String code);
}